using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace Lua
{
	/// <summary>
	/// Structure of "reloadable.json". This file is generated by Ravenfield
	/// Tools Pack when exporting a mod. It is meant to contain the absolute
	/// path of all Ravenscript source files in the mod.
	/// </summary>
	[System.Serializable]
	struct ReloadableJson
	{
		/// <summary>
		/// Absolute path (on HDD) to all TextAssets recently exported by
		/// Ravenfield Tools Pack.
		/// </summary>
		public string[] textAssets;
	}
}
